---
title: "Statistik Covid-19 Kota Bandung (Update 12 Mei 2020)"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: menu
    selfcontained : false
runtime: shiny
---

```{r setup, include=FALSE}
#------------------ Packages ------------------
library(flexdashboard)
library(openxlsx)
library(leaflet)
library(shiny)
library(rgdal)
library(sp)
library(DT)
library(rpostgis)
library(htmltools)
library(rmarkdown)
library(knitr)
library(plotly)
library(leaflet.minicharts)
#------------------ Warna ------------------
confirmed_color <- "purple"
active_color <- "#1f77b4"
recovered_color <- "forestgreen"
death_color <- "red"
#------------------ Data ------------------
bandung<- readOGR("D:/Kerjaan/Covid19/@" ,"kasus bandung")
batas <- readOGR("D:/Kerjaan/LNA", "Kota Bandung")
tabel <- read.xlsx("D:/covid-19.xlsx", sheet = "Prov")
topkec <- read.xlsx("D:/covid-19.xlsx", sheet = "Prov")
daily <- read.xlsx("D:/covid-19.xlsx", sheet = "Daily")
chart <- read.xlsx("D:/covid-19.xlsx", sheet = "Chart")
#------------------ Data ------------------
daily$Tanggal <- as.Date(daily$Tanggal, origin = "1899-12-30")
topkec$Kecamatan <- factor(topkec$Kecamatan, levels = unique(topkec$Kecamatan)[order(topkec$Total.Kasus, decreasing = TRUE)])
jumlahpositif <- 276
jumlahsembuh <- 46
jumlahmeninggal <- 35
jumlahtotal <- jumlahmeninggal +jumlahsembuh+jumlahpositif
```


Rangkuman {data-icon="fas fa-align-center"}
=======================================================================
Row
-----------------------------------------------------------------------
### Total Kasus
```{r}

valueBox(jumlahtotal, icon = "fas fa-user-md", color = "purple")
```

### Positif
```{r}
valueBox(jumlahpositif, icon = "fa-plus", color = "#1f77b4")
```

### Sembuh
```{r}
valueBox(jumlahsembuh, icon = "fa-medkit", color = "forestgreen")
```

### Meninggal
```{r}
valueBox(jumlahmeninggal, 
         icon = "fa-ambulance", color = "red")
```

### Layanan Kedaruratan
```{r}
layanan <- "119 atau 112"
valueBox(layanan, 
         icon = "fa-phone", color = "blue")

```

### Persentase Kesembuhan
```{r}
rate11 <- (jumlahsembuh/jumlahtotal)*100
rate1 <- round(rate11, digits = 2)
gauge(rate1, min = 0, max = 100, symbol = '%',  gaugeSectors(
  success = c(11, 100), warning = c(6, 10), danger = c(0, 5)
))
```

### Persentase Kematian
```{r}
rate22 <- (jumlahmeninggal/jumlahtotal)*100
rate2 <- round(rate22, digits = 2)
gauge(rate2, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(0, 5), warning = c(6, 10 ), danger = c(11, 100)
))
```

Row
-----------------------------------------------------------------------
### Kecamatan Dengan Total Kasus Terbanyak
```{r}
plot_ly(data = topkec , x = ~Kecamatan, y = ~Positif, 
                # text =  ~ Positif, 
                # textposition = 'auto',
                type = "bar", 
                name = "Positif",
                mode = "none",
                marker = list(color = active_color)) %>%
add_trace(y = ~Sembuh, 
                # text =  ~ Sembuh, 
                # textposition = 'auto',
                name = "Sembuh",
                marker = list(color = recovered_color)) %>%
add_trace(y = ~Meninggal, 
                # text =  ~ Meninggal, 
                # textposition = 'auto', 
                name = "Meninggal",
                marker = list(color = death_color)) %>%
layout(title = "", barmode = 'stack',
                 yaxis = list(title = "Total Kasus"),
                 xaxis = list(title = "Kecamatan"),
                 legend = list(x = 0.1, y = 0.9),
                 hovermode = "compare")
```

Row
-----------------------------------------------------------------------
### Akumulasi Kasus Harian
```{r}
plot_ly(data = daily,
                x = ~Tanggal,
                y = ~Positif, 
                name = 'Positif', 
                fillcolor = active_color,
                type = 'scatter',
                mode = 'none', 
                stackgroup = 'one') %>%
add_trace(y = ~Sembuh,
                    name = "Sembuh",
                    fillcolor = recovered_color) %>%
add_trace(y = ~Meninggal,
                    name = "Meninggal",
                    fillcolor = death_color) %>%
layout(title = "",
                 yaxis = list(title = "Akumulasi Kasus"),
                 xaxis = list(title = "Tanggal"),
                 legend = list(x = 0.1, y = 0.9),
                 hovermode = "compare")
```

Peta Sebaran Covid-19 {data-icon="fa-map"}
=======================================================================
**Peta**
```{r}
bins <- c(0, 5, 10, 20, 30, Inf)
pal <- colorBin("Blues", domain = batas$Total, bins = bins)
label1 <- sprintf(
  "<center><strong>%s<strong>%s</center>","Status : ",
  bandung$Status
) %>% lapply(htmltools::HTML)
label2 <- sprintf(
  "<strong>%s<strong>%s<br/><strong>%s<strong>%s<br/><strong>%s<strong>%s<br/><strong>%s<strong>%s<br/>","Kecamatan ",
  batas$WADMKC, "Positif    : ", batas$Positif, "Sembuh : ", batas$Sembuh,"Meninggal : ", batas$Meninggal
) %>% lapply(htmltools::HTML)
label3 <- sprintf(
  "<center><strong>%s<strong>%s</center>","Kecamatan ",
  batas$WADMKC
) %>% lapply(htmltools::HTML)
actpal <- colorFactor(c("red","#1f77b4","forestgreen"), bandung$Status)
leaflet(data = bandung) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = batas, fillColor = "blue", weight = 2 , color = "black", dashArray = 3,
              highlightOptions = highlightOptions(weight = 10, color = "red", fillColor = "yellow"),
              label = label3,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px"), group = "Peta Persebaran Covid-19") %>%
  addCircleMarkers(data = bandung, label = label1,
                   color = ~actpal(Status),clusterOptions = markerClusterOptions(),
                   labelOptions = labelOptions(color = "red"), group = "Peta Persebaran Covid-19")%>%
  addMarkers(
      lng = 107.5983938, lat = -6.8981615,
      label = "RSU Dr. Hasan Sadikin", group = "Rumah Sakit Rujukan",
      labelOptions = labelOptions(noHide = F, direction = "bottom",
                                  style = list(
                                    "color" = "black",
                                    "font-family" = "Arial",
                                    "font-style" = "Bold",
                                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                                    "font-size" = "16px",
                                    "border-color" = "rgba(0,0,0,0.5)"))) %>%
  
  addMarkers(
      lng = 107.6060396, lat = -6.8788486,
      label = "RSTP Dr. H. A. Rotinsulu", group = "Rumah Sakit Rujukan",
      labelOptions = labelOptions(noHide = F, direction = "bottom",
                                  style = list(
                                    "color" = "black",
                                    "font-family" = "Arial",
                                    "font-style" = "Bold",
                                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                                    "font-size" = "16px",
                                    "border-color" = "rgba(0,0,0,0.5)")))%>%
  addMarkers(
      lng = 107.6047986, lat = -6.8639986,
      label = "RSAU Dr. M. Salamun", group = "Rumah Sakit Rujukan",
      labelOptions = labelOptions(noHide = F, direction = "bottom",
                                  style = list(
                                    "color" = "black",
                                    "font-family" = "Arial",
                                    "font-style" = "Bold",
                                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                                    "font-size" = "16px",
                                    "border-color" = "rgba(0,0,0,0.5)")))%>%
  addMarkers(
      lng = 107.6047986, lat = -6.8639986,
      label = "RSAU Dr. M. Salamun", group = "Rumah Sakit Rujukan",
      labelOptions = labelOptions(noHide = F, direction = "bottom",
                                  style = list(
                                    "color" = "black",
                                    "font-family" = "Arial",
                                    "font-style" = "Bold",
                                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                                    "font-size" = "16px",
                                    "border-color" = "rgba(0,0,0,0.5)")))%>%
  addMarkers(
      lng = 107.5964485, lat = -6.9354451,
      label = "RS Immanuel Bandung", group = "Rumah Sakit Rujukan",
      labelOptions = labelOptions(noHide = F, direction = "bottom",
                                  style = list(
                                    "color" = "black",
                                    "font-family" = "Arial",
                                    "font-style" = "Bold",
                                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                                    "font-size" = "16px",
                                    "border-color" = "rgba(0,0,0,0.5)")))%>%
  addMarkers(
      lng = 107.6136797, lat = -6.8939955,
      label = "RS Santo Borromeus", group = "Rumah Sakit Rujukan",
      labelOptions = labelOptions(noHide = F, direction = "bottom",
                                  style = list(
                                    "color" = "black",
                                    "font-family" = "Arial",
                                    "font-style" = "Bold",
                                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                                    "font-size" = "16px",
                                    "border-color" = "rgba(0,0,0,0.5)")))%>%
  addMarkers(
      lng = 107.6430956, lat = -6.9066752,
      label = "RS Santo Yusup Bandung", group = "Rumah Sakit Rujukan",
      labelOptions = labelOptions(noHide = F, direction = "bottom",
                                  style = list(
                                    "color" = "black",
                                    "font-family" = "Arial",
                                    "font-style" = "Bold",
                                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                                    "font-size" = "16px",
                                    "border-color" = "rgba(0,0,0,0.5)")))%>%
  addMarkers(
      lng = 107.6030803, lat = -6.892027,
      label = "RS Advent Bandung", group = "Rumah Sakit Rujukan",
      labelOptions = labelOptions(noHide = F, direction = "bottom",
                                  style = list(
                                    "color" = "black",
                                    "font-family" = "Arial",
                                    "font-style" = "Bold",
                                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                                    "font-size" = "16px",
                                    "border-color" = "rgba(0,0,0,0.5)")))%>%
  addMarkers(
      lng = 107.6691759, lat = -6.9390073,
      label = "RS Al Islam Bandung", group = "Rumah Sakit Rujukan",
      labelOptions = labelOptions(noHide = F, direction = "bottom",
                                  style = list(
                                    "color" = "black",
                                    "font-family" = "Arial",
                                    "font-style" = "Bold",
                                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                                    "font-size" = "16px",
                                    "border-color" = "rgba(0,0,0,0.5)")))%>%
  addMarkers(
      lng = 107.6003952, lat = -6.9154516,
      label = "Santosa Hospital Bandung Central", group = "Rumah Sakit Rujukan",
      labelOptions = labelOptions(noHide = F, direction = "bottom",
                                  style = list(
                                    "color" = "black",
                                    "font-family" = "Arial",
                                    "font-style" = "Bold",
                                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                                    "font-size" = "16px",
                                    "border-color" = "rgba(0,0,0,0.5)")))%>%
  addMarkers(
      lng = 107.6987411, lat = -6.915671,
      label = "RSUD Kota Bandung", group = "Rumah Sakit Rujukan",
      labelOptions = labelOptions(noHide = F, direction = "bottom",
                                  style = list(
                                    "color" = "black",
                                    "font-family" = "Arial",
                                    "font-style" = "Bold",
                                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                                    "font-size" = "16px",
                                    "border-color" = "rgba(0,0,0,0.5)")))%>%
  addMarkers(
      lng = 107.666749, lat = -6.904909,
      label = "RS Hermina Arcamanik", group = "Rumah Sakit Rujukan",
      labelOptions = labelOptions(noHide = F, direction = "bottom",
                                  style = list(
                                    "color" = "black",
                                    "font-family" = "Arial",
                                    "font-style" = "Bold",
                                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                                    "font-size" = "16px",
                                    "border-color" = "rgba(0,0,0,0.5)")))%>%
  addMarkers(
      lng = 107.5913938, lat = -6.9432506,
      label = "RS Khusus Ibu dan Anak Kota Bandung", group = "Rumah Sakit Rujukan",
      labelOptions = labelOptions(noHide = F, direction = "bottom",
                                  style = list(
                                    "color" = "black",
                                    "font-family" = "Arial",
                                    "font-style" = "Bold",
                                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                                    "font-size" = "16px",
                                    "border-color" = "rgba(0,0,0,0.5)")))%>%
  addPolygons(data = batas, fillColor = ~pal(Total),
  weight = 2,
  opacity = 1,
  color = "black",
  dashArray = "3",
  fillOpacity = 0.7,
              label = label2,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px"), group = "Peta Choropleth Covid-19") %>%
  addLegend(position = "bottomright", pal = actpal, values = ~Status, title = "Keterangan", opacity = 0.6, group = "Peta Persebaran Covid-19" ) %>%
  addLegend(position = "bottomright", pal = pal, values = ~batas$Total, title = "Keterangan", opacity = 0.6, group = "Peta Choropleth Covid-19") %>%
  addLayersControl(
   overlayGroups = c("Peta Persebaran Covid-19", "Peta Choropleth Covid-19", "Rumah Sakit Rujukan"),options = layersControlOptions(collapsed = FALSE)) %>%
  hideGroup("Peta Choropleth Covid-19")%>%
  addMiniMap(
    tiles = providers$CartoDB.Positron,
    toggleDisplay = TRUE, position = "bottomleft")%>%
  addEasyButton(easyButton(
    icon="fa-globe", title="Zoom Kota Bandung",
    onClick=JS("function(btn, map){ map.setZoom(12); }")))
```

Grafik {data-icon="fas fa-chart-line"}
=======================================================================
Column
-----------------------------------------------------------------------
### Grafik Kasus Positif
```{r}
plot_ly(data = daily) %>%
  add_trace(
    x = ~Tanggal,
    # y = ~Positif,
    y = ~Positif,
    type = "scatter",
    mode = "lines+markers",
    # name = "Total Kasus",
    name = "Total Kasus",
    line = list(color = active_color),
    marker = list(color = active_color)
  ) %>%
  add_annotations(
    x = as.Date("2020-04-22"),
    y = 182,
    text = "PSBB Bandung Raya",
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -10,
    ay = -50
  ) %>%
  add_annotations(
    x = as.Date("2020-03-17"),
    y = 1,
    text = "Kasus Positif Pertama",
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -10,
    ay = -50
  ) %>%
  layout(
    title = "",
    yaxis = list(title = "Kasus Positif", range = c(0,300)),
    xaxis = list(title = "Tanggal"),
    legend = list(x = 0.1, y = 0.9),
    hovermode = "compare")
```

Column
-----------------------------------------------------------------------
### Grafik Kasus Sembuh
```{r}
plot_ly(data = daily) %>%
  add_trace(
    x = ~Tanggal,
    # y = ~Sembuh,
    y = ~Sembuh,
    type = "scatter",
    mode = "lines+markers",
    # name = "Sembuh",
    name = "Sembuh",
    line = list(color = confirmed_color),
    marker = list(color = confirmed_color)
  ) %>%
  add_annotations(
    x = as.Date("2020-04-22"),
    y = 35,
    text = "PSBB Bandung Raya",
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -10,
    ay = -50
  ) %>%
  add_annotations(
    x = as.Date("2020-03-17"),
    y = 1,
    text = "Kasus Sembuh Pertama",
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -10,
    ay = -50
  ) %>%
  layout(
    title = "",
    yaxis = list(title = "Kasus Sembuh", range = c(0,50)), 
    xaxis = list(title = "Tanggal"),
    legend = list(x = 0.1, y = 0.9),
    hovermode = "compare")
```

Column
-----------------------------------------------------------------------
### Grafik Kasus Meninggal
```{r}
plot_ly(data = daily) %>%
  add_trace(
    x = ~Tanggal,
    # y = ~Meninggal,
    y = ~Meninggal,
    type = "scatter",
    mode = "lines+markers",
    # name = "Meninggal",
    name = "Meninggal",
    line = list(color = active_color),
    marker = list(color = active_color)
  ) %>%
  add_annotations(
    x = as.Date("2020-04-22"),
    y = 32,
    text = "PSBB Bandung Raya",
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -10,
    ay = -50
  ) %>%
  add_annotations(
    x = as.Date("2020-03-23"),
    y = 1,
    text = "Kasus Meninggal Pertama",
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -10,
    ay = -50
  ) %>%
  layout(
    title = "",
    yaxis = list(title = "Kasus Meninggal", range = c(0,50)),
    xaxis = list(title = "Tanggal"),
    legend = list(x = 0.1, y = 0.9),
    hovermode = "compare")
```


Data {data-icon="fas fa-table"}
=======================================================================
### Tabel Covid-19 Kota Bandung
```{r}
datatable(tabel, options = list(
  bPaginate = FALSE
))
```